<?php

declare(strict_types=1);

use App\Foundation\Config;
use App\Foundation\Database;
use App\Foundation\Environment;
use App\Foundation\Logger;
use App\Repositories\BrandRepository;
use App\Repositories\CategoryRepository;
use App\Repositories\ProductImageRepository;
use App\Repositories\ProductRepository;
use App\Repositories\ProductSpecificationRepository;
use App\Services\ImageProcessingException;
use App\Services\ImageProcessor;
use App\Services\ProductImageService;
use App\Services\ProductService;
use App\Services\ProductSpecificationService;
use App\Services\SlugService;
use App\Http\Request;
use App\Http\Response;
use App\Http\Router;
use App\Security\Csrf;

$basePath=dirname(__DIR__); require $basePath.'/vendor/autoload.php'; Environment::load($basePath.'/.env');
$config=new Config(['database'=>require $basePath.'/config/database.php']); $pdo=(new Database($config))->connect();
$failures=[];$test=static function(string $name,callable $fn)use(&$failures):void{try{$fn();echo "PASS: {$name}\n";}catch(Throwable $e){$failures[]=$name.': '.$e->getMessage();echo "FAIL: {$name}\n";}};$assert=static function(bool $condition,string $message='Assertion failed.'):void{if(!$condition)throw new RuntimeException($message);};
$temp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'frigo-phase5-'.bin2hex(random_bytes(6)); mkdir($temp,0700,true); mkdir($temp.DIRECTORY_SEPARATOR.'public',0700,true);
$products=new ProductRepository($pdo);$images=new ProductImageRepository($pdo);$specifications=new ProductSpecificationRepository($pdo);$imageService=new ProductImageService($images,new ImageProcessor(),new Logger($temp.DIRECTORY_SEPARATOR.'test.log'),$temp.DIRECTORY_SEPARATOR.'public');$specService=new ProductSpecificationService($specifications);
$make=static function(string $type,int $width=40,int $height=20)use($temp):string{$path=tempnam($temp,'img-');$image=imagecreatetruecolor($width,$height);$color=imagecolorallocate($image,20,100,180);imagefilledrectangle($image,0,0,$width,$height,$color);if($type==='jpeg')imagejpeg($image,$path,90);elseif($type==='png')imagepng($image,$path);else imagewebp($image,$path,90);imagedestroy($image);return $path;};
$upload=static fn(string $path,string $name='unsafe.php'):array=>['name'=>$name,'type'=>'application/octet-stream','tmp_name'=>$path,'error'=>UPLOAD_ERR_OK,'size'=>filesize($path)];
try {
    $brandId=(int)$pdo->query('SELECT id FROM brands ORDER BY id LIMIT 1')->fetchColumn();$categoryId=(int)$pdo->query('SELECT id FROM categories ORDER BY id LIMIT 1')->fetchColumn();
    if($brandId===0||$categoryId===0)throw new RuntimeException('Phase 5 tests require seeded brand and category data.');
    $productData=['brand_id'=>$brandId,'category_id'=>$categoryId,'name'=>'Phase Five Test','slug'=>'phase-five-test-'.bin2hex(random_bytes(4)),'code'=>null,'price'=>null,'short_description'=>null,'description'=>null,'seo_title'=>null,'seo_description'=>null,'is_featured'=>0,'is_active'=>0];$productId=$products->create($productData);
    $test('Valid JPEG, PNG, and WebP uploads are re-encoded with random WebP names',static function()use($assert,$make,$upload,$imageService,$images,$productId):void{$files=[];foreach(['jpeg','png','webp']as$type)$files[]=$upload($make($type));$multi=['name'=>array_column($files,'name'),'type'=>array_column($files,'type'),'tmp_name'=>array_column($files,'tmp_name'),'error'=>array_column($files,'error'),'size'=>array_column($files,'size')];$assert($imageService->upload($productId,'Midea Test',$multi)===3);$rows=$images->allForProduct($productId);$assert(count($rows)===3&&(int)$rows[0]['is_main']===1);foreach($rows as$row){$assert((bool)preg_match('#^uploads/products/'.$productId.'/[a-f0-9]{32}\.webp$#',$row['image_path']));$assert($row['width']==40&&$row['height']==20);}});
    $test('Fake extension/content and malformed images are rejected',static function()use($assert,$temp,$upload):void{$processor=new ImageProcessor();$fake=$temp.DIRECTORY_SEPARATOR.'fake.jpg';file_put_contents($fake,'<?php echo 1;');try{$processor->process($upload($fake),$temp.DIRECTORY_SEPARATOR.'bad.webp');throw new RuntimeException('Fake content accepted.');}catch(ImageProcessingException){$assert(true);}$malformed=$temp.DIRECTORY_SEPARATOR.'malformed.png';file_put_contents($malformed,"\x89PNG\r\n\x1a\ninvalid");try{$processor->process($upload($malformed),$temp.DIRECTORY_SEPARATOR.'bad2.webp');throw new RuntimeException('Malformed content accepted.');}catch(ImageProcessingException){$assert(true);}});
    $test('Oversized files and excessive dimensions are rejected',static function()use($assert,$temp,$upload,$make):void{$processor=new ImageProcessor();$large=$temp.DIRECTORY_SEPARATOR.'large.jpg';$handle=fopen($large,'wb');fseek($handle,ImageProcessor::MAX_BYTES);fwrite($handle,'x');fclose($handle);try{$processor->process($upload($large),$temp.DIRECTORY_SEPARATOR.'large.webp');throw new RuntimeException('Oversize accepted.');}catch(ImageProcessingException){$assert(true);}$wide=$make('png',ImageProcessor::MAX_SOURCE_DIMENSION+1,1);try{$processor->process($upload($wide),$temp.DIRECTORY_SEPARATOR.'wide.webp');throw new RuntimeException('Dimensions accepted.');}catch(ImageProcessingException){$assert(true);}});
    $test('Resize preserves ratio and never upscales',static function()use($assert,$make,$upload,$temp):void{$processor=new ImageProcessor();$small=$processor->process($upload($make('png',40,20)),$temp.DIRECTORY_SEPARATOR.'small.webp');$large=$processor->process($upload($make('jpeg',2400,1200)),$temp.DIRECTORY_SEPARATOR.'resized.webp');$assert($small===['width'=>40,'height'=>20]);$assert($large===['width'=>2200,'height'=>1100]);});
    $test('Main image changes and deleting main safely promotes first remaining image',static function()use($assert,$images,$imageService,$productId):void{$rows=$images->allForProduct($productId);$assert($imageService->setMain($productId,(int)$rows[1]['id']));$assert((int)$images->findForProduct((int)$rows[1]['id'],$productId)['is_main']===1);$assert($imageService->delete($productId,(int)$rows[1]['id']));$remaining=$images->allForProduct($productId);$assert(count($remaining)===2&&(int)$remaining[0]['is_main']===1);});
    $test('Image ordering is normalized and foreign IDs are rejected',static function()use($assert,$products,$productData,$images,$imageService,$productId,$make,$upload):void{$other=$products->create([...$productData,'slug'=>$productData['slug'].'-other']);$imageService->upload($other,'Other', $upload($make('png')));$foreign=(int)$images->allForProduct($other)[0]['id'];$rows=$images->allForProduct($productId);$ids=array_reverse(array_column($rows,'id'));$assert($imageService->reorder($productId,$ids));$assert(array_column($images->allForProduct($productId),'id')===$ids);$assert(!$imageService->reorder($productId,[$ids[0],$foreign]));});
    $test('Specifications validate, preserve Serbian text, replace, edit, remove, and reorder',static function()use($assert,$specService,$specifications,$productId):void{$valid=$specService->validate(['spec_name'=>['Wi-Fi','Kapacitet hlađenja'],'spec_value'=>['Da','12.000 BTU'],'spec_order'=>[1,0]]);$assert($valid->isValid());$specService->replace($productId,$valid->data);$rows=$specifications->allForProduct($productId);$assert($rows[0]['name']==='Kapacitet hlađenja'&&$rows[1]['name']==='Wi-Fi');$edit=$specService->validate(['spec_name'=>['Energetska klasa'],'spec_value'=>['A++']]);$specService->replace($productId,$edit->data);$rows=$specifications->allForProduct($productId);$assert(count($rows)===1&&$rows[0]['value']==='A++'&&(int)$rows[0]['sort_order']===0);});
    $test('Blank and long specification fields are rejected before existing rows are deleted',static function()use($assert,$specService,$specifications,$productId):void{foreach([['spec_name'=>[''],'spec_value'=>['Da']],['spec_name'=>['Wi-Fi'],'spec_value'=>['']],['spec_name'=>[str_repeat('x',191)],'spec_value'=>['Da']],['spec_name'=>['Opis'],'spec_value'=>[str_repeat('x',501)]]]as$input)$assert(!$specService->validate($input)->isValid());$assert(count($specifications->allForProduct($productId))===1);});
    $test('Specification replacement is scoped to the selected product',static function()use($assert,$products,$productData,$specService,$specifications,$productId):void{$other=$products->create([...$productData,'slug'=>$productData['slug'].'-spec-scope']);$specService->replace($other,[['name'=>'Gas','value'=>'R32']]);$specService->replace($productId,[['name'=>'Wi-Fi','value'=>'Da']]);$assert($specifications->allForProduct($other)[0]['value']==='R32');});
    $test('Phase 5 writes are authenticated, POST-only, and require valid CSRF',static function()use($assert):void{$called=false;$authenticated=false;$router=new Router();$router->add('POST','/admin/products/{id}/images',static function()use(&$called):Response{$called=true;return Response::html('ok');});$router->protectAdminWith(static function()use(&$authenticated):?Response{return $authenticated?null:Response::redirect('/admin/login',302);});$assert($router->dispatch(new Request('POST','/admin/products/1/images'))->status===302&&!$called);$authenticated=true;$assert($router->dispatch(new Request('GET','/admin/products/1/images'))->status===404);$_SESSION['_csrf_token']=str_repeat('c',64);$csrf=new Csrf();$assert(!$csrf->validate(null)&&!$csrf->validate(str_repeat('x',64))&&$csrf->validate(str_repeat('c',64)));});
    $test('Product deletion removes database rows and physical image files',static function()use($assert,$products,$productData,$imageService,$images,$make,$upload,$temp):void{$id=$products->create([...$productData,'slug'=>$productData['slug'].'-delete']);$imageService->upload($id,'Delete',$upload($make('jpeg')));$row=$images->allForProduct($id)[0];$absolute=$temp.DIRECTORY_SEPARATOR.'public'.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$row['image_path']);$assert(is_file($absolute));$service=new ProductService($products,new BrandRepository($GLOBALS['pdo']),new CategoryRepository($GLOBALS['pdo']),new SlugService(),$imageService);$assert($service->delete($id)&&!is_file($absolute)&&$products->find($id)===null);});
} finally { $cleanup=$pdo->prepare("DELETE FROM products WHERE slug LIKE 'phase-five-test-%'");$cleanup->execute(); }
$remove=static function(string $path)use(&$remove):void{if(!is_dir($path))return;foreach(scandir($path)?:[]as$item)if($item!=='.'&&$item!=='..'){ $child=$path.DIRECTORY_SEPARATOR.$item;is_dir($child)?$remove($child):@unlink($child);}@rmdir($path);};$remove($temp);
if($failures!==[]){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "All Phase 5 image and specification checks passed.\n";
