<?php
$e = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
$rangeLabels = ['7' => 'Last 7 days', '30' => 'Last 30 days', 'all' => 'All time'];
$chartData = json_encode(['labels' => array_column($dailyViews, 'view_date'), 'values' => array_map('intval', array_column($dailyViews, 'views'))], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_THROW_ON_ERROR);
$hasChartData = array_sum(array_map('intval', array_column($dailyViews, 'views'))) > 0;
?>
<div class="page-heading"><div><p class="eyebrow">Catalog interest</p><h1>Analytics</h1><p>Approximate product interest without invasive visitor tracking.</p></div></div>
<nav class="range-tabs" aria-label="Analytics time range"><?php foreach ($rangeLabels as $value => $label): $selected = $range === (string) $value; ?><a class="<?= $selected ? 'current' : '' ?>" href="/admin/analytics?range=<?= $e($value) ?>" <?= $selected ? 'aria-current="page"' : '' ?>><?= $e($label) ?></a><?php endforeach; ?></nav>
<section class="stats" aria-label="Analytics summary"><article><strong><?= $e($summary['total_views']) ?></strong><span>Total views</span></article><article><strong><?= $e($summary['viewed_products']) ?></strong><span>Products with views</span></article></section>
<section class="panel"><h2>Views over time</h2><div class="chart-wrap"><canvas id="views-chart" aria-label="Daily product views chart" role="img"<?= !$hasChartData ? ' hidden' : '' ?>></canvas><p id="chart-empty"<?= $hasChartData ? ' hidden' : '' ?>>No product views in this period.</p></div><script type="application/json" id="views-chart-data"><?= $chartData ?></script></section>
<div class="analytics-grid"><section class="panel"><h2>Most viewed products</h2><?php if ($topProducts === []): ?><p>No product views in this period.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Product</th><th>Brand</th><th>Category</th><th>Views</th></tr></thead><tbody><?php foreach ($topProducts as $product): ?><tr><td><?= $e($product['name']) ?></td><td><?= $e($product['brand_name']) ?></td><td><?= $e($product['category_name']) ?></td><td><?= $e($product['views']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<section class="panel"><h2>Most viewed categories</h2><?php if ($topCategories === []): ?><p>No category views in this period.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Category</th><th>Views</th></tr></thead><tbody><?php foreach ($topCategories as $category): ?><tr><td><?= $e($category['name']) ?></td><td><?= $e($category['views']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section></div>
