<?php
$e=static fn(mixed $value):string=>htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$v=static fn(string $key):string=>$e($values[$key]??'');
$error=static function(string $key)use($errors,$e):void{if(isset($errors[$key]))echo '<span class="field-error">'.$e($errors[$key]).'</span>';};
$productId=(int)($productId??0);$images=$images??[];$specifications=$specifications??[];
?>
<div class="page-heading"><div><h1><?= $title==='Create product'?'Dodaj proizvod':'Izmeni proizvod' ?></h1><p>Unesite osnovne podatke o klima uređaju.</p></div><a href="/admin/products">Nazad na proizvode</a></div>
<?php if($flash):?><p class="flash flash-<?= $e($flash['type']) ?>" role="status"><?= $e($flash['message']) ?></p><?php endif;?>
<?php if($errors):?><div class="flash flash-error" role="alert"><strong>Ispravite označena polja.</strong></div><?php endif;?>
<form class="admin-form" method="post" action="<?= $e($action) ?>"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><section class="panel"><h2>Podaci o proizvodu</h2><div class="form-grid">
<label class="wide">Naziv proizvoda<input name="name" value="<?= $v('name') ?>" maxlength="255" required><?php $error('name');?></label><label>Brend<select name="brand_id" required><option value="">Izaberite brend</option><?php foreach($brands as $brand):?><option value="<?= $e($brand['id']) ?>" <?= (int)($values['brand_id']??0)===(int)$brand['id']?'selected':'' ?>><?= $e($brand['name']) ?><?= (int)$brand['is_active']===0?' (skriven)':'' ?></option><?php endforeach;?></select><?php $error('brand_id');?></label><label>Kategorija<select name="category_id" required><option value="">Izaberite kategoriju</option><?php foreach($categories as $category):?><option value="<?= $e($category['id']) ?>" <?= (int)($values['category_id']??0)===(int)$category['id']?'selected':'' ?>><?= $e($category['name']) ?><?= (int)$category['is_active']===0?' (skrivena)':'' ?></option><?php endforeach;?></select><?php $error('category_id');?></label><label>Model / šifra proizvoda<input name="code" value="<?= $v('code') ?>" maxlength="150" placeholder="Na primer: MSAGBU-12HRFN8"><?php $error('code');?></label><label>Cena<input name="price" value="<?= $v('price') ?>" inputmode="decimal" placeholder="Opciono" min="0" step="0.01"><?php $error('price');?></label><label class="wide">Kratak opis<textarea name="short_description" maxlength="2000" rows="4"><?= $v('short_description') ?></textarea><?php $error('short_description');?></label><label class="wide">Detaljan opis<textarea name="description" maxlength="50000" rows="10"><?= $v('description') ?></textarea><?php $error('description');?></label></div><div class="checks"><label class="check"><input type="checkbox" name="is_featured" value="1" <?= (int)($values['is_featured']??0)===1?'checked':'' ?>> Istaknut proizvod</label><label class="check"><input type="checkbox" name="is_active" value="1" <?= (int)($values['is_active']??0)===1?'checked':'' ?>> Aktivan i vidljiv</label></div></section><button class="button" type="submit">Sačuvaj proizvod</button></form>
<?php if($productId>0):?>
<section class="panel product-media"><h2>Slike</h2><p>Dodajte JPG, PNG ili WebP slike do 10 MB. Optimizacija je automatska.</p><form class="upload-form" method="post" action="/admin/products/<?= $e($productId) ?>/images" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><label class="button file-button">Dodaj slike<input type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple required></label><span data-file-count>Nijedna slika nije izabrana.</span><button type="submit">Otpremi</button></form>
<?php if($images===[]):?><div class="image-placeholder" role="img" aria-label="Proizvod nema sliku"><span>Nema slike</span></div><?php else:?><form method="post" action="/admin/products/<?= $e($productId) ?>/images/order"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><div class="image-gallery" data-image-list><?php foreach($images as $image):?><article class="image-card" data-image-item><input type="hidden" name="image_ids[]" value="<?= $e($image['id']) ?>"><img src="/<?= $e($image['image_path']) ?>" alt="<?= $e($image['alt_text']) ?>" width="<?= $e($image['width']) ?>" height="<?= $e($image['height']) ?>"><div class="image-card-meta"><?php if((int)$image['is_main']===1):?><strong class="badge active">Glavna</strong><?php else:?><button class="link-button" type="submit" formaction="/admin/products/<?= $e($productId) ?>/images/<?= $e($image['id']) ?>/main">Postavi kao glavnu</button><?php endif;?><div><button type="button" class="link-button" data-move="up">↑ Gore</button><button type="button" class="link-button" data-move="down">↓ Dole</button></div><button class="link-button danger" type="submit" formaction="/admin/products/<?= $e($productId) ?>/images/<?= $e($image['id']) ?>/delete" formnovalidate data-confirm="Obrisati ovu sliku?">Obriši</button></div></article><?php endforeach;?></div><button type="submit">Sačuvaj redosled slika</button></form><?php endif;?></section>
<section class="panel"><h2>Specifikacije</h2><p>Dodajte samo podatke koji su korisni kupcu.</p><form class="specification-form" method="post" action="/admin/products/<?= $e($productId) ?>/specifications" data-spec-form><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><div data-spec-list><?php foreach($specifications as $index=>$specification):?><div class="spec-row" data-spec-row><input type="hidden" name="spec_order[]" value="<?= $e($index) ?>"><label>Naziv<input name="spec_name[]" value="<?= $e($specification['name']) ?>" maxlength="190" required></label><label>Vrednost<input name="spec_value[]" value="<?= $e($specification['value']) ?>" maxlength="500" required></label><div class="row-actions"><button type="button" class="link-button" data-spec-move="up">↑</button><button type="button" class="link-button" data-spec-move="down">↓</button><button type="button" class="link-button danger" data-spec-remove>Ukloni</button></div></div><?php endforeach;?></div><div class="spec-buttons"><button type="button" class="button secondary" data-spec-add>+ Dodaj specifikaciju</button><button type="submit">Sačuvaj specifikacije</button></div></form><template data-spec-template><div class="spec-row" data-spec-row><input type="hidden" name="spec_order[]" value="0"><label>Naziv<input name="spec_name[]" maxlength="190" required></label><label>Vrednost<input name="spec_value[]" maxlength="500" required></label><div class="row-actions"><button type="button" class="link-button" data-spec-move="up">↑</button><button type="button" class="link-button" data-spec-move="down">↓</button><button type="button" class="link-button danger" data-spec-remove>Ukloni</button></div></div></template></section>
<?php else:?><section class="panel"><h2>Slike i specifikacije</h2><p>Najpre sačuvajte proizvod. Zatim ćete ovde jednostavno dodati slike i specifikacije.</p></section><?php endif;?>
